AbstractSQLOptimiser.ometajs
AbstractSQLRules2SQL.ometajs

Adding the lookahead results in an ~64% gain in the abstract sql compilation time in the tests

Optimisations

---

package.json
src/AbstractSQLCompiler.ts
src/AbstractSQLOptimiser.ts
src/AbstractSQLRules2SQL.ts
test/abstract-sql/is-distinct.ts
test/abstract-sql/test.coffee

This is split into two commits, one that has the prettier bump and `'postgres'`  -> `Engines.postgres` conversions, and the other that actually adds the new support, so you may want to review individually

 Add support for `IsDistinctFrom`/`IsNotDistinctFrom`

---

package.json
src/AbstractSQLCompiler.ts
src/AbstractSQLRules2SQL.ts
test/odata/stress.coffee

This helps massively as the number of bind vars increases (200k was fine for abstract-sql-compiler), and actually moves the bottleneck to the odata parsing side instead: https://github.com/balena-io-modules/odata-to-abstract-sql/pull/46 

Switch to a lookup table for finding existing bind var entries

---

src/AbstractSQLCompiler.ts

This matches how we handle table/trigger creation and avoids issues
with running create schema statements concurrently

Only create functions if they don't already exist

---

.circleci/config.yml
package.json
src/AbstractSQLCompiler.ts
src/AbstractSQLRules2SQL.ts
test/odata/test.coffee
test/sbvr/pilots.coffee
test/sbvr/test.coffee
tsconfig.json

* Drop support for node 6/8
* Update tsconfig to target es2018
* Convert all returned promises to native promises instead of bluebird
* Update to @balena/sbvr-types 3.0.0
* Improve typings - this is https://github.com/balena-io-modules/abstract-sql-compiler/pull/79 but brought into this as it is a major change in terms of typings
* Rename to @balena/abstract-sql-compiler

7.x major version

---

src/AbstractSQLCompiler.ts

Remove accidental `necessity` from the `AbstractSqlField` types

---

src/AbstractSQLCompiler.ts
src/AbstractSQLRules2SQL.ts

Allow compiling `*QueryNode`s to direct strings without binds

---

src/AbstractSQLCompiler.ts

Fix `containsNode` when that node type is at the top level

---

src/AbstractSQLCompiler.ts
test/abstract-sql/get-rule-referenced-fields.ts

This works on the assumption that it is a rule query that should always
return true and allows ignoring more modification cases where they
cannot change the result from true to false

Add a `getRuleReferencedFields` which is tailored for rules

---

package.json
src/AbstractSQLRules2SQL.ts

This became unnecessary when @balena/sbvr-types added the concept of
cast types since that now specifies how to cast a SERIAL type

Remove now unnecessary hack for casting SERIAL types

---

src/AbstractSQLRules2SQL.ts

This reverts commit 187bc075d237a2ced731d0a026ca25aa3e0f5540.

Revert "Remove now unnecessary hack for casting SERIAL types"

---

src/AbstractSQLOptimiser.ts
src/AbstractSQLRules2SQL.ts
test/abstract-sql/functions_wrapper.ts

Supprt date_trunc postgres date function
for DateValue
Signed-off-by: fisehara harald@balena.io

Supprt date_trunc postgres date function

---

src/AbstractSQLCompiler.ts
src/AbstractSQLRules2SQL.ts
test/abstract-sql/functions_wrapper.ts

FunctionWrapper type for ReferencedField
Signed-off-by: fisehara <harald@balena.io>

Support for non postgres db engines

---

src/referenced-fields.ts
test/abstract-sql/get-rule-referenced-fields.ts

Since it's possible for them to behave in a way that violates the
safety checks we'll disable them until we can add specific checks
for the HAVING clause

Avoid the operation type optimization for HAVING clauses

---

package.json
src/AbstractSQLCompiler.ts
test/abstract-sql/schema-informative-reference.ts
test/sbvr/reference-type.js

An informative reference is just an int field that points
to another tables id field - like foreign key without constraints
or foregein key cascades.
Signed-off-by: fisehara <harald@balena.io>

Add informative reference dataType to schema tests

---

src/AbstractSQLCompiler.ts
src/AbstractSQLOptimiser.ts
src/AbstractSQLRules2SQL.ts
test/abstract-sql/aggregate.ts
test/odata/filterby.js

isNumericValue is evaluated in arithmetic expressions if operands in expression can be used as numericValues.
In SQL statements arithmetic expressions like add/sub are supported for date values.
DateArithmetic nodes need input dependent typing.
Signed-off-by: fisehara <harald@balena.io>

Fix date fields used inside arithmetic expressions

---

src/AbstractSQLCompiler.ts

This is intended to be used to target tables differently for reads vs
writes, eg where you might read from a view/definition but want to
write to a physical table instead

Add `modifyFields`/`modifyName` to table definition

---

src/AbstractSQLRules2SQL.ts
test/odata/expand.js

This increases the minimum postgres version for AggregateJSON from 9.2 to 9.3 but it is likely that other places already require postgres
\>=9.3 and as such this should not increase the minimum version at all.
If it does somehow manage to then increasing the minimum from a 2012 postgres to 2013 should still be fine

Change AggregateJSON to use `JSON_AGG` instead of `ARRAY_TO_JSON`+`ARRAY_AGG`

---

src/AbstractSQLCompiler.ts
src/AbstractSQLSchemaOptimiser.ts

This optimizes and normalizes rules before compiling the schema.
Signed-off-by: Carol Schulze <carol@balena.io>

Optimize schema during compilation

---

package.json
src/AbstractSQLCompiler.ts
src/referenced-fields.ts
test/abstract-sql/schema-checks.ts
test/abstract-sql/schema-informative-reference.ts
test/abstract-sql/schema-rule-optimization.ts
test/abstract-sql/schema-rule-to-check.ts
test/abstract-sql/schema-views.ts
test/sbvr/pilots.js

After every write, pine has to rerun all rules from the model to ensure consistency. These rules run over the entire database, sometimes causing some queries to run for too long against what should be a simple write.
This commit adds a mechanism to help with this issue by narrowing the set of rows that each rule should touch to those rows that were actually changed.
Implementing this mechanism safely is doable and not necessarily complex code-wise, but requires a deep modifications from the current architecture. This commit adds a restricted form instead where we only narrow the rows of the root table that were changed. If any other table was changed then narrowing is a no op.
It can be proved that this is always safe as long as the root table is selected from only once and the rule is …

Add binds for affected IDs in compiled rules

---

package.json
src/AbstractSQLCompiler.ts
src/AbstractSQLOptimiser.ts
src/AbstractSQLRules2SQL.ts
test/abstract-sql/insert-query.ts

This also deprecates the legacy use of direct true/false entries

Support boolean nodes in a ValuesNode

---

src/AbstractSQLCompiler.ts
src/AbstractSQLOptimiser.ts

It can in fact be a lot of different things and that is now also reflected in the typing

Revert tightening of `OrderBy` to only field nodes

---

src/AbstractSQLCompiler.ts

Deprecate `AliasableFromTypeNodes` type as it's redundant

---

package.json
src/AbstractSQLCompiler.ts

Update TypeScript to 5.4.3

---

src/AbstractSQLCompiler.ts
src/AbstractSQLSchemaOptimiser.ts

See: https://balena.zulipchat.com/#narrow/stream/346007-balena-io.2FbalenaCloud/topic/Pine.20Partial.20UNIQUE.20Index.20based.20rules

Add support for partial unique indexes

---

src/referenced-fields.ts

Add Lower unary node for countTableSelects optimization

---

src/AbstractSQLCompiler.ts
src/AbstractSQLOptimiser.ts
src/AbstractSQLRules2SQL.ts
test/abstract-sql/comparisons.ts

Add EqualsAny node

---

src/AbstractSQLCompiler.ts
src/AbstractSQLOptimiser.ts
src/AbstractSQLRules2SQL.ts

Clarify the `['Bind', string, string]` form of `BindNode` is legacy

---

src/AbstractSQLOptimiser.ts
src/AbstractSQLRules2SQL.ts

This matches the fact that the result type is unknown/can be anything and also matches the existing typing

Treat `CaseNode` as an unknown type node as expected

---

package.json

See: https://balena.fibery.io/Work/Project/Make-release-assets-publicly-available-and-maintained-1177

Allow sbvr-types v10 as peer dependency

---

src/AbstractSQLCompiler.ts
test/sbvr/pilots.ts
test/sbvr/reference-type.ts

This should have slightly less edge cases than trying to execute the function and checking that it does not already exist, particularly if we add arguments or similar in future where the `PERFORM` command would need to match precisely

Switch to using a duplicate function exception to handle double function creation

---

src/AbstractSQLCompiler.ts

This can be used to optimize the schema without yet committing to a specific database engine, useful for a pass over abstractSql prior to generating a db engine specific sql model

Export an `optimizeSchema` variant that is database engine agnostic

---

src/AbstractSQLCompiler.ts
src/AbstractSQLOptimiser.ts
src/AbstractSQLRules2SQL.ts
test/abstract-sql/dates.ts
test/odata/test.ts

---
See: https://balena.fibery.io/Work/Project/Use-time-zone-based-timestamps-for-PineJS-dates-965

Add optional time zone argument for DateTrunc

---

package.json

---
See: https://balena.fibery.io/Work/Project/Use-time-zone-based-timestamps-for-PineJS-dates-965
Allow for `sbvr-types` v11 for https://github.com/balena-io-modules/sbvr-types/pull/112

Allow sbvr-types v11
