AbstractSQLCompiler.coffee
Didn't touch `AbstractSQLCompiler.js` assuming you update it before publishing a version. Let me know if you'd like me to change it with this PR.
Connects-To: #5 
Change-Type: patch
=> Fixed exception thrown while trying to compile schema

AbstractSQLCompiler.coffee, AbstractSQLRules2SQL.ometajs, CHANGELOG.md
This warrants a major version bump.
=> Fix rule compilation that would not pass bindings along

src/AbstractSQLCompiler.ts
=> Support explicit table/alias nodes for the getXFields functions

src/AbstractSQLCompiler.ts
=> Fix the deprecated implicit alias check to account for implicit tables

src/AbstractSQLCompiler.ts
=> Fix `FromNode` typing

package.json, test/odata/test.coffee
=> Update to odata-to-abstract-sql v3.0.0

package.json, src/AbstractSQLCompiler.ts, typings/sbvr-types.d.ts
=> Improve typings

src/AbstractSQLOptimiser.ts
=> Fix `FieldNode`s being detected as deprecated aliases

package.json, src/AbstractSQLCompiler.ts, test/abstract-sql/get-referenced-fields.ts, test/mocha.opts, tsconfig.build.json, tsconfig.json
=> Add tests for `getReferencedFields`

src/AbstractSQLCompiler.ts
Linked to https://github.com/balena-io-modules/odata-to-abstract-sql/pull/39 and https://github.com/balena-io/pinejs/pull/293
=> Add support for computed fields

src/AbstractSQLCompiler.ts, test/abstract-sql/get-referenced-fields.ts
=> Use an abstract-sql-optimiser prepass to simplify getReferencedFields

src/AbstractSQLCompiler.ts, test/abstract-sql/get-referenced-fields.ts
=>  Improve aliased from handling in `getReferencedFields`

package.json, src/AbstractSQLRules2SQL.ts, test/odata/stress.coffee, test/odata/test.coffee
=> Optimise finding of existing binds when adding a bind variable

src/AbstractSQLCompiler.ts, test/sbvr/pilots.coffee, test/sbvr/test.coffee
=> Add support for resolving directly circular dependencies on postgres

src/AbstractSQLOptimiser.ts, test/abstract-sql/nested-in-optimisations.ts
This means the IN conversion can include the nested ORs when possible
=> Improve OR to IN and AND to NOT IN optimisations

package.json, src/AbstractSQLCompiler.ts, src/AbstractSQLOptimiser.ts, src/AbstractSQLRules2SQL.ts, test/sbvr/pilots.coffee
=> Add support for basic check constraints

src/AbstractSQLCompiler.ts
=> Fix `compileRule` typings

src/AbstractSQLCompiler.ts, test/sbvr/pilots.coffee
=> Fix CHECK syntax

src/AbstractSQLCompiler.ts, src/AbstractSQLOptimiser.ts, src/AbstractSQLRules2SQL.ts, test/abstract-sql/joins.ts
=> Add support for `CrossJoin`

src/AbstractSQLCompiler.ts
=> Trim trigger names to the max of 63 characters

src/AbstractSQLCompiler.ts
=> Fix query type check

.lintstagedrc, package.json, src/AbstractSQLCompiler.ts, src/AbstractSQLOptimiser.ts, src/AbstractSQLRules2SQL.ts, test/abstract-sql/get-referenced-fields.ts, test/abstract-sql/joins.ts, test/abstract-sql/nested-in-optimisations.ts
=> Update resin-lint to 3.x and use it for auto-linting

src/AbstractSQLCompiler.ts, src/AbstractSQLOptimiser.ts, src/AbstractSQLRules2SQL.ts, test/abstract-sql/coalesce.ts
=> Add support for coalesce

src/AbstractSQLCompiler.ts
Signed-off-by: Andreas Fitzek <andreas@balena.io>
=> 📝♻️ : Improve RelationshipMapping typing and docs

src/AbstractSQLCompiler.ts, src/AbstractSQLOptimiser.ts, src/AbstractSQLRules2SQL.ts, test/abstract-sql/test.coffee, test/odata/filterby.coffee, test/odata/test.coffee
=> Reduce lodash usage

src/AbstractSQLCompiler.ts
=> Improve `BindNode` typing

README.md, package.json, src/AbstractSQLCompiler.ts, src/AbstractSQLRules2SQL.ts, test/mocha.opts
Update sbvr-types from 3.1.0 to 3.1.2
=> Update sbvr-types and make use of `castType`

src/AbstractSQLCompiler.ts
=> Remove some type casts

src/AbstractSQLOptimiser.ts, test/abstract-sql/not-not-optimisations.ts
=> Fix the `NOT(NOT(...))` optimization

src/AbstractSQLCompiler.ts, test/abstract-sql/schema-checks.ts
=> Add check constraint support at the table level

package.json, src/AbstractSQLCompiler.ts, src/AbstractSQLSchemaOptimiser.ts, test/abstract-sql/schema-rule-to-check.ts
Currently this can optimize certain rules into check constraints
=> Add an `optimizeSchema` function

src/AbstractSQLCompiler.ts, src/AbstractSQLRules2SQL.ts
=> Improve typings for compilation results

src/AbstractSQLCompiler.ts
See: https://github.com/balena-io/open-balena-api/pull/510#discussion_r546872607
Signed-off-by: Thodoris Greasidis <thodoris@balena.io>
=> Improve Relationship typings

src/AbstractSQLOptimiser.ts, test/abstract-sql/and-or-boolean-optimisations.ts
=> Optimize out booleans from AND/OR where possible

src/AbstractSQLOptimiser.ts, src/AbstractSQLRules2SQL.ts, test/abstract-sql/and-or-boolean-optimisations.ts
=> Optimize away AND/ORs with false/true respectively

src/AbstractSQLOptimiser.ts, test/abstract-sql/empty-query-optimisations.ts
=> Optimize EXISTS/NOT EXISTS for empty queries

src/AbstractSQLOptimiser.ts, src/AbstractSQLRules2SQL.ts, test/abstract-sql/is-distinct.ts, test/odata/filterby.js
=> Optimize Is[Not]DistinctFrom and [Not]Exists for non-null values

src/AbstractSQLCompiler.ts, src/AbstractSQLOptimiser.ts, src/AbstractSQLRules2SQL.ts
=> Convert some lodash usage to native equivalents

src/AbstractSQLSchemaOptimiser.ts, test/abstract-sql/schema-rule-to-check.ts
=> Fix schema optimizations when table and resource names are different

package.json, src/AbstractSQLSchemaOptimiser.ts
=> Optimize the abstract sql of rules when running `optimizeSchema`

test/abstract-sql/schema-rule-optimization.ts
=> Add test for optimizeSchema optimizing rules

src/AbstractSQLCompiler.ts, src/referenced-fields.ts
=> Separate code relating to referenced fields out of the main file

src/referenced-fields.ts
=> Fix `getModifiedFields` for `UpsertQuery`s

src/referenced-fields.ts, test/abstract-sql/get-rule-referenced-fields.ts
=> Enable narrowing down create/delete referenced fields for nested exists

tsconfig.json
=> Enable strict options by default and only disable specific ones

package.json
=> Re-enable all tests

src/AbstractSQLRules2SQL.ts
=> Allow duration seconds to be nullable

package.json
Update sbvr-types from 3.4.2 to 3.4.3
=> Update sbvr-types to 3.4.3

src/AbstractSQLOptimiser.ts, src/AbstractSQLRules2SQL.ts
=> Add support for `CurrentTimestamp`/`CurrentDate` nodes

package.json, src/AbstractSQLOptimiser.ts, src/AbstractSQLRules2SQL.ts
=> Relax the restrictions on `ORDER BY` as it doesn't just allow fields

src/AbstractSQLCompiler.ts
=> Improve typing for `LikeNode`

src/AbstractSQLCompiler.ts, src/AbstractSQLRules2SQL.ts
=> Fix GroupByNode typings

src/AbstractSQLCompiler.ts, src/AbstractSQLOptimiser.ts, src/AbstractSQLRules2SQL.ts
=> Add support for `HAVING` clauses

src/referenced-fields.ts, test/abstract-sql/get-rule-referenced-fields.ts
=> Add support for `From` nodes in rule referenced fields

package.json, src/AbstractSQLCompiler.ts
=> Expose `isAliasNode` helper

.npmrc
=> Dev: Disable package-lock.json generation

test/abstract-sql/aggregate.ts
=> CI: Add several abstract-sql unit tests

src/AbstractSQLRules2SQL.ts, test/abstract-sql/aggregate.ts
=> Fix Right SQL generation

test/abstract-sql/aggregate.ts
=> CI: Add more abstract-sql unit tests

package.json
=> Update typescript from 4.6.4 to 4.9.3

package.json
=> Update ts-node from 10.7.0 to 10.9.1

package.json
=> Update lint-staged from 12.4.1 to 13.0.3

package.json
=> Update @balena/lint from 6.2.0 to 6.2.1

package.json
=> Update @balena/lf-to-abstract-sql from 4.5.1 to 4.5.2

package.json
=> Update @balena/odata-parser from 2.2.9 to 2.4.2

package.json
=> Update @balena/sbvr-parser from 1.4.1 to 1.4.2

package.json
=> Update @balena/sbvr-types from 3.4.7 to 3.4.8

package.json
=> Update @types/lodash from 4.14.182 to 4.14.189

package.json
=> Update @types/node from 10.17.60 to 18.11.9

package.json
=> Dev: Move types to dev dependencies

.husky/pre-commit
=> Dev: Update pre-commit hook

src/AbstractSQLCompiler.ts, src/AbstractSQLOptimiser.ts, src/AbstractSQLRules2SQL.ts, test/abstract-sql/json.ts
=> Add ToJSON/ExtractJSONPathAsText functions

src/referenced-fields.ts
=> Add support for getting the modified fields of an aliased query

package.json, src/AbstractSQLOptimiser.ts
=> Fix deprecation notice module name

package.json
=> Fix: move @balena/odata-to-abstract-sql to dev dependencies

package.json, src/AbstractSQLCompiler.ts, src/AbstractSQLSchemaOptimiser.ts, src/referenced-fields.ts, test/abstract-sql/get-rule-referenced-fields.ts, test/abstract-sql/schema-rule-to-check.ts, test/sbvr/pilots.js
=> Add support for rules optimizations when using COUNT(*) = 0

src/AbstractSQLCompiler.ts, src/AbstractSQLOptimiser.ts, src/AbstractSQLRules2SQL.ts
Signed-off-by: Carol Schulze <carol@balena.io>
=> Add the AbstractSql node `Any`

package.json, test/odata/filterby.js, test/odata/resource_parsing.js
=> Tests: update @balena/odata-to-abstract-sql to 5.8

src/AbstractSQLRules2SQL.ts, test/abstract-sql/dates.ts, test/abstract-sql/math.ts
Resolves: #184
See: https://balena.zulipchat.com/#narrow/stream/346007-balena-io.2FbalenaCloud/topic/absract-sql-compiler.20math.20operator.20precedence
=> Wrap composite math operations with parenthesis

src/AbstractSQLCompiler.ts, src/referenced-fields.ts, test/abstract-sql/cast.ts
=> Adds Cast node type to tree parsing

src/AbstractSQLCompiler.ts, src/AbstractSQLOptimiser.ts, src/AbstractSQLRules2SQL.ts, test/abstract-sql/math.ts
=> Add `BitwiseAnd`/`BitwiseShiftRight` node types

src/AbstractSQLCompiler.ts
=> Add more node typings

src/AbstractSQLCompiler.ts
=> Improve node typings

src/AbstractSQLCompiler.ts, src/AbstractSQLOptimiser.ts, src/AbstractSQLRules2SQL.ts
=> Tighten the `isXValue` function typings

src/AbstractSQLCompiler.ts, src/AbstractSQLRules2SQL.ts, src/referenced-fields.ts
=> Remove typing for non-existent JSON node

src/AbstractSQLCompiler.ts
=> Fix DateNode/AnyNode typings

src/AbstractSQLCompiler.ts, src/AbstractSQLRules2SQL.ts
=> Fix TS errors for the latest sbvrTypes

package.json, src/AbstractSQLCompiler.ts, src/AbstractSQLRules2SQL.ts, src/AbstractSQLSchemaOptimiser.ts, test/odata/test.js, test/sbvr/test.js
Update @balena/sbvr-types from 4.0.0 to 5.0.0
=> Update @balena/sbvr-types to 5.0.0

package.json
Update @balena/sbvr-types from 5.0.0 to 6.0.0
=> Update @balena/sbvr-types to 6.0.0

src/AbstractSQLRules2SQL.ts
=> Cast Big Serial to integer

src/AbstractSQLCompiler.ts, src/AbstractSQLOptimiser.ts
=> Adds `EndsWithNode` and `ContainsNode` typings

src/AbstractSQLRules2SQL.ts, test/abstract-sql/comparisons.ts
On top of #226 
See: https://balena.zulipchat.com/#narrow/stream/346007-balena-io.2FbalenaCloud/topic/pinejs.2015/near/358435946
=> Wrap composite comparison operations with parenthesis when necessary

package.json
=> Fix @balena/sbvr-types peer dependency version specifier

package.json, test/odata/expand.js, test/odata/filterby.js, test/odata/orderby.js, test/odata/select.js
=> Update dev dependencies

package.json, src/AbstractSQLCompiler.ts, src/AbstractSQLRules2SQL.ts, test/odata/filterby.ts, test/odata/test.ts, test/sbvr/test.ts
=> Update @balena/lint to 9.x

src/AbstractSQLCompiler.ts, test/sbvr/pilots.ts, test/sbvr/reference-type.ts
=> Add missing ; in trigger creation $$ section

src/AbstractSQLRules2SQL.ts, test/abstract-sql/is-distinct.ts, test/odata/expand.ts, test/odata/filterby.ts, test/odata/resource_parsing.ts, test/odata/select.ts, test/odata/stress.ts
=> Extend `IsNotDistinctFrom` paren omission to more atomic node types

src/AbstractSQLCompiler.ts
=> Export `abstractSqlContainsNode` helper function

package.json, test/odata/filterby.ts
=> Tests: Update @balena/odata-to-abstract-sql to 8.0.1

src/abstract-sql-compiler.ts, src/abstract-sql-optimizer.ts, test/abstract-sql/alias-optimisations.ts, test/odata/resource-parsing.ts
=> Optimize away unnecessary aliasing

src/abstract-sql-compiler.ts
https://balena.fibery.io/Work/Project/1766
=> Create computed functions after table definitions

src/abstract-sql-optimizer.ts, src/abstract-sql-rules-to-sql.ts, test/abstract-sql/test.ts
https://balena.fibery.io/Work/Project/1766
=> Handle optimizing/compiling table nodes in the standard manner
